from one_big_thing.learning.constants import AWARENESS, PRACTITIONER, WORKING

additional_learning = {
    "any": {
        "section_title": "All levels",
        "courses": [
            {
                "title": "Living is a risky business with Jen Rogers",
                "link": "https://www.ted.com/talks/jennifer_rogers_living_is_a_risky_business",
                "provider": "TEDx",
                "type": "Video",
                "duration": 16,
            },
            {
                "title": "Statistically speaking from ONS",
                "link": "https://sites.libsyn.com/397223/website",
                "provider": "Office for National Statistics",
                "type": "Podcast",
                "duration": "Various",
            },
            {
                "title": "5 great TED talks about data visualisation",
                "link": "https://coolinfographics.com/blog/2016/10/10/5-great-ted-talks-about-dataviz.html",
                "provider": "Cool Infographics",
                "type": "Multiple",
                "duration": "Various",
            },
            {
                "title": "How juries are fooled by statistics with Peter Donnelly",
                "link": "https://www.ted.com/talks/peter_donnelly_how_juries_are_fooled_by_statistics/transcript",
                "provider": "TED Talks",
                "type": "Video",
                "duration": 21,
            },
            {
                "title": "Digital garage from Google",
                "link": "https://learndigital.withgoogle.com/digitalgarage/courses?category=data",
                "provider": "Google",
                "type": "Course",
                "duration": "Various",
            },
            {
                "title": "Byte sized learning",
                "link": "https://www.youtube.com/playlist?list=PLxXq2x8c-H0JRa0YX3RO8KSYVoEnuYtjw",
                "provider": "Government Analytical Function",
                "type": "Video",
                "duration": "Various",
            },
            {
                "title": "Analytical literacy",
                "link": "https://analysis-function-learning.github.io/analytical_literacy/#/",
                "provider": "Government Analytical Function",
                "type": "Course",
                "duration": 120,
            },
            {
                "title": "Introduction to data quality from the Government Data Quality Hub",
                "link": "https://bpi-courses.github.io/Introduction_to_Data_Quality/",
                "provider": "Government Data Quality Hub",
                "type": "Course",
                "duration": 40,
            },
            {
                "title": "Role of the Data Standards Authority",
                "link": "https://www.gov.uk/government/groups/data-standards-authority",
                "provider": "Data Standards Authority",
                "type": "Webpage",
                "duration": "Various",
            },
            {
                "title": "How we use real-time mobility data to provide situational awareness with Tom L",
                "link": "https://vimeo.com/860893596/f7c399f9ba",
                "provider": "Cabinet Office",
                "type": "Video",
                "duration": 11,
            },
            {
                "title": "Brief introduction to data science with Tom C",
                "link": "https://vimeo.com/860893541/a64d95515f",
                "provider": "Cabinet Office",
                "type": "Video",
                "duration": 4,
            },
            {
                "title": "Data catalogues with Darminder and Shane",
                "link": "https://vimeo.com/860893385/e31d6518d8",
                "provider": "Cabinet Office",
                "type": "Video",
                "duration": 3,
            },
            {
                "title": "Introduction to economics in government with Vladd and Joely",
                "link": "https://vimeo.com/860893092/89938e4fb9",
                "provider": "Cabinet Office",
                "type": "Video",
                "duration": 5,
            },
            {
                "title": "Introduction to Official Statistics with Richard, Martin and Darren",
                "link": "https://vimeo.com/860892433/8b57224e68",
                "provider": "Cabinet Office",
                "type": "Video",
                "duration": 12,
            },
            {
                "title": "A data driven approach to team goal setting with Cailin",
                "link": "https://vimeo.com/860892338/66fae73762",
                "provider": "Cabinet Office",
                "type": "Video",
                "duration": 5,
            },
            {
                "title": "Policy evaluation in goverment with Lizzie and Philipp",
                "link": "https://vimeo.com/860891715/9aafb8d725",
                "provider": "Cabinet Office",
                "type": "Video",
                "duration": 11,
            },
            {
                "title": "Using data and AI to make decisions with Ben and Mallory",
                "link": "https://vimeo.com/860891900/6c51b1d56a",
                "provider": "Cabinet Office",
                "type": "Video",
                "duration": 16,
            },
            {
                "title": "Moving from spreadsheets to coding with Hanna",
                "link": "https://vimeo.com/863524596/0977b482e3",
                "provider": "Cabinet Office",
                "type": "Video",
                "duration": 8,
            },
            {
                "title": "Data and decision-making with Dr Laura Gilbert",
                "link": "https://vimeo.com/869081373/21d5499980",
                "provider": "Cabinet Office",
                "type": "Video",
                "duration": 6,
            },
            {
                "title": "Tableau with Matthew and Ajiri",
                "link": "https://vimeo.com/869108122/9c458cea46",
                "provider": "Cabinet Office",
                "type": "Video",
                "duration": 3,
            },
        ],
    },
    AWARENESS: {
        "section_title": "Level 1 - Awareness",
        "courses": [
            {
                "title": "Multiply Numeracy Quiz from Skills for Life Campaign",
                "link": "https://skillsforlife.campaign.gov.uk/courses/multiply/",
                "provider": "Skills for Life Campaign",
                "type": "Webpage",
                "duration": "Various",
            },
            {
                "title": "Data Skills",
                "link": "https://ukdataservice.ac.uk/learning-hub/data-skills-modules/",
                "provider": "UK Data Service",
                "type": "Course",
                "duration": "Various",
            },
            {
                "title": "Data visualisation",
                "link": "https://analysisfunction.civilservice.gov.uk/support/communicating-analysis/introduction-to-data-visualisation-e-learning/",  # noqa: E501
                "provider": "Government Analysis Function",
                "type": "Course",
                "duration": "Various",
            },
            {
                "title": "Analysing evidence: effective collaboration",
                "link": "https://learn.civilservice.gov.uk/courses/0EuGjOBwR62fFpnOhTilHQ",
                "provider": "Civil Service Learning",
                "type": "Course",
                "duration": 36,
            },
            {
                "title": "Data visualisation 101",
                "link": "https://learn.civilservice.gov.uk/courses/2PAR3NQyT-GOg5-7bVZaog",
                "provider": "Civil Service Learning",
                "type": "Course",
                "duration": 60,
            },
            {
                "title": "Numeracy resources",
                "link": "https://www.nationalnumeracy.org.uk/",
                "provider": "National Numeracy Organisation",
                "type": "Webpage",
                "duration": "Various",
            },
            {
                "title": "Skillswise",
                "link": "https://www.bbc.co.uk/teach/skillswise/maths/zfdymfr",
                "provider": "BBC",
                "type": "Webpage",
                "duration": "Various",
            },
        ],
    },
    WORKING: {
        "section_title": "Level 2 - Working",
        "courses": [
            {
                "title": "Trust vs trustworthiness with Onora O'Neill",
                "link": "https://www.youtube.com/watch?v=XWwTYy9k5nc",
                "provider": "British Science Association",
                "type": "Video",
                "duration": 10,
            },
            {
                "title": "Let's talk about data quality!",
                "link": "https://www.youtube.com/playlist?list=PLxXq2x8c-H0J0xmd9Mcx5o3UiCwaTmelc",
                "provider": "Government Analysis Function",
                "type": "Video",
                "duration": 80,
            },
            {
                "title": "YouTube playlist",
                "link": "https://www.youtube.com/channel/UCVY5YwwgpprO_2KEYz-cVrw/videos?view=0",
                "provider": "Government Analysis Function",
                "type": "Video",
                "duration": "Various",
            },
            {
                "title": "Data Quality",
                "link": "https://learn.civilservice.gov.uk/courses/GyZgKWc0Tz6ZIfvDSiuO1Q",
                "provider": "Civil Service Learning",
                "type": "Course",
                "duration": 80,
            },
            {
                "title": "Why we should all care about data",
                "link": "https://vimeo.com/875157624",
                "provider": "Cabinet Office and the Office for National Statistics",
                "type": "Video",
                "duration": 0,
            },
            {
                "title": "So you think you know about data",
                "link": "https://vimeo.com/875172535/8f1620e5f8",
                "provider": "Cabinet Office and the Office for National Statistics",
                "type": "Video",
                "duration": 46,
            },
            {
                "title": "The good, the bad and the unfair - all about data quality and ethics",
                "link": "https://vimeo.com/875184473/66fe939198",
                "provider": "Cabinet Office and the Office for National Statistics",
                "type": "Video",
                "duration": 45,
            },
            {
                "title": "Economy...society...pandemic...what would YOU have done?",
                "link": "",
                "provider": "Cabinet Office and the Office for National Statistics",
                "type": "Video",
                "duration": 0,
            },
            {
                "title": "Data in action",
                "link": "",
                "provider": "Cabinet Office and the Office for National Statistics",
                "type": "Video",
                "duration": 0,
            },
        ],
    },
    PRACTITIONER: {
        "section_title": "Level 3 - Practitioner",
        "courses": [
            {
                "title": "Open Data Institute Blog",
                "link": "https://www.theodi.org/",
                "provider": "Open Data Institute",
                "type": "Webpage",
                "duration": "Various",
            },
            {
                "title": "The work of DataKind",
                "link": "https://www.datakind.org/",
                "provider": "DataKind",
                "type": "Webpage",
                "duration": "Various",
            },
            {
                "title": "Transformers United, Stanford University's CS25 Lectures",
                "link": "https://www.youtube.com/playlist?list=PLoROMvodv4rNiJRchCzutFw5ItR_Z27CM",
                "provider": "Stanford University",
                "type": "Video",
                "duration": "Various",
            },
            {
                "title": "Building resilience in government using data science",
                "link": "https://www.turing.ac.uk/news/data-science-should-be-used-build-resilience-government-decision-making-new-turing-white-paper",  # noqa: E501
                "provider": "Alan Turing Institute",
                "type": "White paper",
                "duration": "Various",
            },
            {
                "title": "The Data Playbook toolkit",
                "link": "https://preparecenter.org/toolkit/data-playbook-beta-toolkit/",
                "provider": "Global Disaster Preparedness Centre",
                "type": "Course",
                "duration": "Various",
            },
            {
                "title": "LLM course",
                "link": "https://docs.cohere.com/docs/llmu",
                "provider": "LLM University",
                "type": "Course",
                "duration": "Various",
            },
            {
                "title": "Introduction to LLM with Mark Reidl",
                "link": "https://mark-riedl.medium.com/a-very-gentle-introduction-to-large-language-models-without-the-hype-5f67941fa59e",  # noqa: E501
                "provider": "Mark Riedl",
                "type": "Webpage",
                "duration": "Various",
            },
            {
                "title": "LangChain tutorials",
                "link": "https://www.youtube.com/watch?v=_v_fgW2SkkQ&list=PLqZXAkvF1bPNQER9mLmDbntNfSpzdDIU5",
                "provider": "Data Independent",
                "type": "Video",
                "duration": "Various",
            },
        ],
    },
}
