# Generated by Django 3.2.20 on 2023-07-07 14:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("last_token_sent_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("invited_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("invite_accepted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("totp_key", models.CharField(blank=True, max_length=255, null=True)),
                ("last_otp", models.CharField(blank=True, max_length=8, null=True)),
                ("title", models.CharField(max_length=100)),
                ("link", models.URLField(blank=True, null=True)),
                ("learning_type", models.CharField(blank=True, max_length=5, null=True)),
                ("time_to_complete", models.IntegerField()),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Completion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("last_token_sent_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("invited_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("invite_accepted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("totp_key", models.CharField(blank=True, max_length=255, null=True)),
                ("last_otp", models.CharField(blank=True, max_length=8, null=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="learning.course")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("last_token_sent_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("invited_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("invite_accepted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("totp_key", models.CharField(blank=True, max_length=255, null=True)),
                ("last_otp", models.CharField(blank=True, max_length=8, null=True)),
                ("name", models.CharField(max_length=256)),
                ("data", models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
    ]
