# Generated by Django 3.2.20 on 2023-07-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0002_auto_20230711_1312"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_marked_complete",
            field=models.BooleanField(default=False),
        ),
    ]
