# Generated by Django 3.2.20 on 2023-07-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0003_add_user_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
