# Generated by Django 3.2.20 on 2023-07-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0004_auto_20230718_1324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="learning_type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
