# Generated by Django 3.2.20 on 2023-07-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0007_auto_20230719_1249"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learning",
            name="learning_type",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
