# Generated by Django 3.2.20 on 2023-07-19 12:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0007_surveyresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="Learning",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("link", models.URLField(blank=True, null=True)),
                ("learning_type", models.CharField(blank=True, max_length=5, null=True)),
                ("time_to_complete", models.IntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="learning.course"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Completion",
        ),
    ]
