# Generated by Django 3.2.20 on 2023-07-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0009_alter_learning_learning_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profession",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
