# Generated by Django 3.2.20 on 2023-07-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0011_auto_20230726_1553"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="competency_level",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="is_special_course",
            field=models.BooleanField(default=False),
        ),
    ]
