# Generated by Django 3.2.20 on 2023-08-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0013_alter_course_time_to_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="learning",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
