# Generated by Django 3.2.20 on 2023-08-13 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0014_learning_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_external_user",
        ),
    ]
