# Generated by Django 3.2.20 on 2023-09-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0015_remove_user_is_external_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="learning",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
