# Generated by Django 3.2.20 on 2023-09-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0016_auto_20230905_1612"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_api_user",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
