# Generated by Django 3.2.20 on 2023-09-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0016_auto_20230905_1612"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_api_access",
            field=models.BooleanField(default=False),
        ),
    ]
