# Generated by Django 3.2.22 on 2023-10-16 08:04

from django.db import migrations, models

import one_big_thing.learning.models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0017_user_is_api_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", one_big_thing.learning.models.UserManager()),
            ],
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["department", "grade", "profession", "has_completed_pre_survey", "has_completed_post_survey"],
                name="learning_us_departm_081e46_idx",
            ),
        ),
    ]
