# Generated by Django 3.2.22 on 2023-10-16 07:41

from django.db import migrations

import one_big_thing.learning.models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0017_user_is_api_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", one_big_thing.learning.models.UserManager()),
            ],
        ),
    ]
