# Generated by Django 3.2.20 on 2023-09-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0017_user_is_api_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_api_user",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
