# Generated by Django 3.2.22 on 2023-10-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0018_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="satisfaction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VERY_DISSATISFIED", "Very dissatisfied"),
                    ("DISSATISFIED", "Dissatisfied"),
                    ("NO_OPINION", "No opinion"),
                    ("SATISFIED", "Satisfied"),
                    ("VERY_SATISFIED", "Very satisfied"),
                ],
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="take_part_in_user_research",
            field=models.CharField(choices=[("yes", "Yes"), ("no", "No")], max_length=3),
        ),
    ]
