# Generated by Django 3.2.22 on 2023-10-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0019_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="learning_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WRITTEN_RESOURCE", "Blog, article, book or other written resource"),
                    ("CIVIL_SERVICE_LIVE", "Civil Service Live event"),
                    ("CONVERSATION", "Conversation with colleagues"),
                    ("EVENT_CENTRAL", "Event - central"),
                    ("EVENT_DEPT", "Event - departmental"),
                    ("EVENT_EXTERNAL", "Event - external"),
                    ("FORMAL_TRAINING_CENTRAL", "Formal training - central"),
                    ("FORMAL_TRAINING_DEPT", "Formal training - departmental"),
                    ("FORMAL_TRAINING_EXTERNAL", "Formal training - external"),
                    ("INFORMAL_TRAINING", "Informal training (on-the-job training)"),
                    ("PODCAST_AUDIO", "Podcast or other audio"),
                    ("VIDEO", "Video or documentary"),
                    ("OTHER", "Other"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="learning",
            name="learning_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WRITTEN_RESOURCE", "Blog, article, book or other written resource"),
                    ("CIVIL_SERVICE_LIVE", "Civil Service Live event"),
                    ("CONVERSATION", "Conversation with colleagues"),
                    ("EVENT_CENTRAL", "Event - central"),
                    ("EVENT_DEPT", "Event - departmental"),
                    ("EVENT_EXTERNAL", "Event - external"),
                    ("FORMAL_TRAINING_CENTRAL", "Formal training - central"),
                    ("FORMAL_TRAINING_DEPT", "Formal training - departmental"),
                    ("FORMAL_TRAINING_EXTERNAL", "Formal training - external"),
                    ("INFORMAL_TRAINING", "Informal training (on-the-job training)"),
                    ("PODCAST_AUDIO", "Podcast or other audio"),
                    ("VIDEO", "Video or documentary"),
                    ("OTHER", "Other"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="surveyresult",
            name="survey_type",
            field=models.CharField(choices=[("pre", "pre"), ("post", "post")], max_length=128),
        ),
    ]
