# Generated by Django 3.2.22 on 2023-12-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_department'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='learning_us_departm_a9c393_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_completed_post_survey',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_completed_pre_survey',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department', 'grade', 'profession'], name='learning_us_departm_501828_idx'),
        ),
    ]
