# Generated by Django 3.2.22 on 2023-10-17 13:56

import django.db.models.deletion
from django.db import migrations, models


def populate_department_model(apps, schema_editor):
    User = apps.get_model("learning", "User")
    Department = apps.get_model("learning", "Department")

    for user in User.objects.all():
        user.new_department = Department.objects.get(code=user.department)
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0020_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="new_department",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="learning.department"
            ),
        ),
        migrations.RunPython(populate_department_model),
    ]
