# Generated by Django 3.2.22 on 2023-10-17 13:56

import django.db.models.deletion
from django.db import migrations, models


def populate_department_model(apps, schema_editor):
    User = apps.get_model("learning", "User")
    Department = apps.get_model("learning", "Department")

    for user in User.objects.all():
        user.new_department = Department.objects.get(code=user.department)
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0020_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="new_department",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="learning.department"
            ),
        ),
        migrations.RunPython(populate_department_model),
        migrations.RemoveIndex(
            model_name="user",
            name="learning_us_departm_081e46_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.RenameField(
            model_name="user",
            old_name="department",
            new_name="old_department",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="new_department",
            new_name="department",
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["department", "grade", "profession", "has_completed_pre_survey", "has_completed_post_survey"],
                name="learning_us_departm_a9c393_idx",
            ),
        ),
    ]
