# Generated by Django 3.2.22 on 2023-10-25 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0018_add_index_to_user"),
        ("learning", "0021_department"),
    ]

    operations = []
