# Generated by Django 3.2.22 on 2023-10-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0021_user_new_department"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="learning_us_departm_081e46_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.RenameField(
            model_name="user",
            old_name="department",
            new_name="old_department",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="new_department",
            new_name="department",
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["department", "grade", "profession", "has_completed_pre_survey", "has_completed_post_survey"],
                name="learning_us_departm_a9c393_idx",
            ),
        ),
    ]
