name: Check code

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'develop'

jobs:
  check_web:
    name: Check Python

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
        pip install -r requirements-dev.lock

    - name: Run Python code checks
      run: |
        make check-python-code

  check_migrations:
    name: Check migrations

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          docker-compose build web
          docker-compose run web python manage.py makemigrations --check

  run_tests:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: |
        make test